# Generated by Django 5.0.7 on 2024-07-26 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='material',
            field=models.FileField(default=django.utils.timezone.now, upload_to='objects/materials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdmodel',
            name='color',
            field=models.JSONField(default={'a': 1.0, 'b': 0.0, 'g': 0.0, 'r': 0.0}),
        ),
    ]
