# Generated by Django 5.0.7 on 2024-07-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_object_material_alter_tdmodel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdmodel',
            name='textures',
        ),
        migrations.AddField(
            model_name='object',
            name='textures',
            field=models.ManyToManyField(null=True, to='api.texture'),
        ),
    ]
