# Generated by Django 5.0.7 on 2024-08-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tdmodel_textures_object_textures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='objectimage',
            old_name='url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='object',
            name='textures',
        ),
        migrations.AddField(
            model_name='texture',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.object'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='image',
            field=models.ImageField(upload_to='textures/'),
        ),
    ]
